apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchlist-frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: go-redis
        image: hmanikkothu/watchlist:v1
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_HOST
          value: redis-watchlist-db
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 8080
  selector:
    app: frontend