apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 3
  template:
    metadata:
      labels:
        app: watchlist
        tier: frontend
    spec:
      containers:
      - name: go-redis
        image: hmanikkothu/watchlist:v1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: REDIS_HOST
          value: redis-watchlist
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: watchlist
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 8080
  selector:
    app: watchlist
    tier: frontend